CREATE TABLE billing_checkout_sessions (
  id CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  plan_key VARCHAR(80) NOT NULL,
  plan_price_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(40) NULL,
  status ENUM('prepared','pending','completed','expired','cancelled','failed') NOT NULL DEFAULT 'prepared',
  idempotency_key VARCHAR(190) NOT NULL,
  external_session_id VARCHAR(190) NULL,
  checkout_url VARCHAR(1000) NULL,
  expires_at DATETIME NULL,
  completed_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_billing_checkout_tenant_idempotency (tenant_id, idempotency_key),
  KEY idx_billing_checkout_status (status, expires_at),
  KEY idx_billing_checkout_external (provider, external_session_id),
  CONSTRAINT fk_billing_checkout_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_billing_checkout_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_billing_checkout_plan FOREIGN KEY (plan_key) REFERENCES saas_plans(plan_key),
  CONSTRAINT fk_billing_checkout_price FOREIGN KEY (plan_price_id) REFERENCES saas_plan_prices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE billing_webhook_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider VARCHAR(40) NOT NULL,
  external_event_id VARCHAR(190) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  tenant_id BIGINT UNSIGNED NULL,
  status ENUM('received','processed','failed','ignored') NOT NULL DEFAULT 'received',
  error_message VARCHAR(1000) NULL,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_billing_webhook_event (provider, external_event_id),
  KEY idx_billing_webhook_status (status, created_at),
  CONSTRAINT fk_billing_webhook_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE billing_subscription_actions (
  id CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  action_type ENUM('pause','resume','cancel','change_plan') NOT NULL,
  current_plan_key VARCHAR(80) NOT NULL,
  target_plan_key VARCHAR(80) NULL,
  target_price_id BIGINT UNSIGNED NULL,
  provider VARCHAR(40) NULL,
  status ENUM('prepared','pending','succeeded','failed','needs_attention') NOT NULL DEFAULT 'prepared',
  idempotency_key VARCHAR(190) NOT NULL,
  error_message VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  expires_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_billing_action_tenant_idempotency (tenant_id, idempotency_key),
  KEY idx_billing_action_status (status, created_at),
  CONSTRAINT fk_billing_action_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_billing_action_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_billing_action_current_plan FOREIGN KEY (current_plan_key) REFERENCES saas_plans(plan_key),
  CONSTRAINT fk_billing_action_target_plan FOREIGN KEY (target_plan_key) REFERENCES saas_plans(plan_key),
  CONSTRAINT fk_billing_action_target_price FOREIGN KEY (target_price_id) REFERENCES saas_plan_prices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
