CREATE TABLE analytics_sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  social_account_id BIGINT UNSIGNED NOT NULL,
  platform ENUM('instagram','tiktok','linkedin') NOT NULL,
  status ENUM('running','completed','failed','skipped') NOT NULL DEFAULT 'running',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  records_received INT UNSIGNED NOT NULL DEFAULT 0,
  error_message VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_analytics_sync_tenant_platform (tenant_id, platform, started_at),
  CONSTRAINT fk_analytics_sync_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_analytics_sync_account FOREIGN KEY (social_account_id) REFERENCES social_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE social_post_metrics_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  brand_id BIGINT UNSIGNED NOT NULL,
  social_account_id BIGINT UNSIGNED NOT NULL,
  calendar_entry_id BIGINT UNSIGNED NULL,
  publication_job_id BIGINT UNSIGNED NULL,
  platform ENUM('instagram','tiktok','linkedin') NOT NULL,
  external_post_id VARCHAR(255) NOT NULL,
  metric_date DATE NOT NULL,
  impressions BIGINT UNSIGNED NULL,
  reach BIGINT UNSIGNED NULL,
  views BIGINT UNSIGNED NULL,
  likes BIGINT UNSIGNED NULL,
  comments BIGINT UNSIGNED NULL,
  shares BIGINT UNSIGNED NULL,
  saves BIGINT UNSIGNED NULL,
  clicks BIGINT UNSIGNED NULL,
  follows BIGINT UNSIGNED NULL,
  watch_time_seconds BIGINT UNSIGNED NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_post_metrics_day (social_account_id, external_post_id, metric_date),
  KEY idx_post_metrics_tenant_date (tenant_id, metric_date),
  KEY idx_post_metrics_brand_platform (brand_id, platform, metric_date),
  CONSTRAINT fk_post_metrics_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_post_metrics_brand FOREIGN KEY (brand_id) REFERENCES brands(id),
  CONSTRAINT fk_post_metrics_account FOREIGN KEY (social_account_id) REFERENCES social_accounts(id),
  CONSTRAINT fk_post_metrics_entry FOREIGN KEY (calendar_entry_id) REFERENCES calendar_entries(id),
  CONSTRAINT fk_post_metrics_job FOREIGN KEY (publication_job_id) REFERENCES publication_jobs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE editorial_performance_signals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  brand_id BIGINT UNSIGNED NOT NULL,
  platform ENUM('instagram','tiktok','linkedin') NOT NULL,
  signal_key VARCHAR(120) NOT NULL,
  signal_value DECIMAL(18,6) NOT NULL,
  sample_size INT UNSIGNED NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  calculated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_editorial_signals_brand_platform (tenant_id, brand_id, platform, calculated_at),
  CONSTRAINT fk_editorial_signals_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_editorial_signals_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
