FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build:web

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
